package tec.lass.zazil_app.model
import tec.lass.zazil_app.R
/**
 * Clase que representa una colección de temas.
 */
val temas = listOf(
    Tema ("Tips para cuidar tu salud menstrual.", R.drawable.cuidarsalud, "Mantener una buena salud menstrual es muy importante. Aquí te compartimos algunos tips para lograrlo…", "¿Qué es la salud menstrual?\n" + "Abarca aspectos del manejo de la higiene menstrual y otros factores (salud, bienestar, igualdad de género, educación, el empoderamiento de personas menstruantes).\n" + "\n ¡Usa ropa que te deje transpirar! \n" + "Evita usar ropa muy ajustada o ropa de tela sintética, ya que aumentan la humedad, el calor y la irritación.\n" + "\n ¡Lávate de manera correcta!\n" + "Tu vulva y vagina son súper sensibles, debes tener mucho cuidado. \n" +"\n Practica un deporte \n" + "Te ayudará a reducir dolores menstruales.", Zazil = false, Menst = true, Dato = false),
    Tema ("¿Cómo lavar mi toalla ZAZIL?", R.drawable.comolavar, "¿Sabes cómo lavar tu toalla Zazil? ¡ES MUY FÁCIL! Aquí te mostramos los pasos para lavar tu toalla y reutilizarla. ", "Paso 1: Remoja tu toalla en agua fría por no más de 4 horas (puedes agregar agua oxigenada).\n" + "\n Paso 2: Lava tu toalla con jabón neutro, evita el uso de suavizantes. \n" + "\n Paso 3: Enjuaga con abundante agua.\n" + "Paso 4: Deja secar tu toalla a la luz del Sol", Zazil = true, Menst = false, Dato = false), // ZAZIL
    //Tema ("Datos sobre el uso de toallas desechables", R.drawable.ic_carrito, "Uso de aprox 4800 tampones durante la vida fértil", "Tampones", Zazil = false, Menst = false, Dato = true), // DATOS
    Tema ("Hablemos de pobreza menstrual", R.drawable.pobrezamenst, "En México, el 15% de las personas menstruantes no cuentan ingresos suficientes para toallas.", "¿Qué es la pobreza menstrual?\n" + "Es la incapacidad de permitirse productos para la higiene íntima femenina.\n" + "\n ¿Cuáles son las principales causas?\n" + "La menstruación está estigmatizada en todo el mundo. Muchas niñas y mujeres tampoco pueden pagar los productos de higiene menstrual. \n" + "\n ¿Por qué es un problema? \n" + "La mala higiene menstrual puede causar riesgos para la salud física.", Zazil = false, Menst = true, Dato = false), // La menstruación
    Tema ("Beneficios de usar toallas ZAZIL", R.drawable.beneficios, "¡Conoce los beneficios de las Toallas Zazil! ¡Transforma tu cuidado menstrual y siente la diferencia!", "1. Disfrutarás de tu comodidad: Sus materiales absorbentes te permiten poder utilizarla de 4 a 6 horas sin preocupaciones de mancharte. \n" + "\n 2. Evitarás químicos: Al estar elaboradas de algodón, las toallas son libres de químicos.\n" + "\n 3. Salud e higiene: Evitarás irritaciones y reacciones alérgicas por sus materiales suaves, ligeros e hipoalergénicos.", Zazil = true, Menst = false, Dato = false), // ZAZIL
    Tema ("Las toallas sanitarias también contaminan", R.drawable.contaminacion, "Debemos disminuir la contaminación de los mares. Toallas reutilizables ayudan al medio ambiente ", "Según lo indica un estudio de la Sociedad de Conservación Marina, las toallas sanitarias son de los productos que más se tiran en las playas y océanos. \n" + "\n Según la ONU, se estima que quien usa toallas sanitarias genera alrededor de 60 kilogramos de residuos en toda su vida.", Zazil = false, Menst = false, Dato = true), // La menstruación
    //Tema ("Características del ciclo menstrual", R.drawable.ic_launcher_foreground, "Conoce las características del ciclo menstrual", "Ciclo menstrual", Zazil = false, Menst = true, Dato = false), // La menstruación
    //Tema ("Síndrome premenstrual", R.drawable.ic_launcher_foreground, "Te explicamos qué es el síndrome premenstrual", "Síndrome premenstrual", Zazil = false, Menst = true, Dato = false), // La menstruación
    //Tema ("Metales pesados en tampones", R.drawable.ic_launcher_foreground, "Te explicamos qué son los metales pesados en tampones", "Metales pesados",  Zazil = false, Menst = false, Dato = true), // DATOS
    //Tema ("Licencia menstrual", R.drawable.ic_launcher_foreground, "Te explicamos qué es la licencia menstrual", "Licencia menstrual",  Zazil = false, Menst = false, Dato = true), // DATOS
    //Tema ("Mi primera menstruación", R.drawable.ic_launcher_foreground, "Cómo saber si es tu primera menstruación", "Primera menstruación",  Zazil = false, Menst = true, Dato = false), // La menstruación
    Tema ("Las estaciones pueden afectar el ciclo menstrual", R.drawable.estaciones, "¿Conoces aquellos beneficios del verano? Empecemos a amar cada estación del año.", "Hay estudios que señalan que los rayos del sol influyen en la menstruación \n" + "\n En concreto, si antes de la ovulación de una mujer (justo antes de que le venga la regla) hace más Sol, es probable que su ciclo menstrual sea más breve ",  Zazil = false, Menst = false, Dato = true), // La menstruación)
)